In [24]:
import warnings
warnings.filterwarnings('ignore')


In [38]:
from pandas.plotting import scatter_matrix

%matplotlib inline
import numpy as np
import datetime
import matplotlib as mpl 
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme()
from sklearn.datasets import make_blobs
import pandas as pd
import hvplot.pandas
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn import preprocessing
from sklearn import utils

from pylab import mpl, plt
import datetime
import tensorflow as tf
from tensorflow import keras
pd.set_option('display.max_rows', 2000)
pd.set_option('display.max_columns', 2000)
pd.set_option('display.width', 1000)

In [39]:
from tensorflow.keras.datasets import mnist 


(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [40]:
"""
train_images and train_labels form the training set, the data that the model will learn from.
The Model will be tested on the test set, test_images and test_labels.

The images are encoded as np arrays, and the labels are an array of digits, ranging from 0:9
Images and labels have a one-to-one correspondence

"""

display(train_images.shape)

display(len(train_labels))

display(test_images.shape)

display(len(test_labels))

display(test_labels)

(60000, 28, 28)

60000

(10000, 28, 28)

10000

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [41]:
"""
# The network architecture.
The core building block of neural networks is the layer, a data-processing module that you can think of as a filter for data
Data does in and comes out in a more usefull form. Layers extract representations out of the data fed into them.
Most deep learning consists of chaining together simple layers that will implement a for, of progressive data distillation.


"""


from tensorflow.keras import models 
from tensorflow.keras import layers

network = models.Sequential()


# dense|fully connected neural layer. 
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
# a 10-way layer, will return an array of 10 probabikity scores summing to 1.
network.add(layers.Dense(10, activation='softmax'))

In [42]:
"""
To make the network ready for training, we need to pick three more things, as part 
of the compilation step:

* A loss function -- How the network will be able to measure its performance on the training data, and thus how it will 
    be able to steer itself in the right direction.

* An optimizer -- The mechanism through which the network updates itself based on the data it sees and its loss function

* Metrics to monitor during training and testing -- Here, we'll only care about accuracy.
    (fraction of images correctly classified).
    
"""


network.compile(optimizer='rmsprop',
               loss='categorical_crossentropy',
               metrics=['accuracy'])

In [43]:
"""
Before training, we'll preprocess the data by reshaping it into the shape the network expects and scaling it
so the all values are in the [0, 1] interval. Previosly, our training images, for instance,
were stored in an array of shape (60000, 28, 28) of type uint8 with values in the [0, 255] interval.
We transform it into a float32 array of shape (60000. 28 * 28) with values between 0 and 1.
"""

train_images = train_images.reshape((60000, 28 * 28))

train_images = train_images.astype('float') / 255

In [44]:
test_images = test_images.reshape((10000, 28 * 28))

test_images = test_images.astype('float') / 255

In [47]:
# We also need to categorically encode the labels

from tensorflow.keras.utils import to_categorical


train_labels = to_categorical(train_labels)

test_labels = to_categorical(test_labels)

In [48]:
# We are now ready to train the network which in keras is done via a call to the networks fir metthod.
# We fit the model to its training data

network.fit(train_images, train_labels,epochs=10, batch_size=128)

Train on 60000 samples
Epoch 1/10
60000/60000 [==============================] - 2s 38us/sample - loss: 0.2586 - acc: 0.9258
Epoch 2/10
60000/60000 [==============================] - 2s 37us/sample - loss: 0.1044 - acc: 0.9691
Epoch 3/10
60000/60000 [==============================] - 2s 39us/sample - loss: 0.0694 - acc: 0.9796
Epoch 4/10
60000/60000 [==============================] - 2s 36us/sample - loss: 0.0499 - acc: 0.9849
Epoch 5/10
60000/60000 [==============================] - 2s 35us/sample - loss: 0.0381 - acc: 0.9883
Epoch 6/10
60000/60000 [==============================] - 2s 35us/sample - loss: 0.0293 - acc: 0.9914
Epoch 7/10
60000/60000 [==============================] - 2s 36us/sample - loss: 0.0225 - acc: 0.9936
Epoch 8/10
60000/60000 [==============================] - 2s 39us/sample - loss: 0.0170 - acc: 0.9952
Epoch 9/10
60000/60000 [==============================] - 2s 35us/sample - loss: 0.0132 - acc: 0.9961
Epoch 10/10
60000/60000 [==============================] - 

In [49]:
"""
Two quantities are displayed during training: the loss of the network over the training data,
and the accuracy of the network over the training data.


Let's check that the model performs well on the test set, too:
"""

test_loss, test_acc = network.evaluate(test_images, test_labels)

print('test_acc:',  test_acc)


10000/10000 [==============================] - 0s 18us/sample - loss: 0.0737 - acc: 0.9815
test_acc: 0.9815


In [59]:
"""
# Data representaions for neural networks
In general, all current machine learning systems use tensors as their basic data structure. 

Tensor: at its core, a tensor is a container for data-- almost always numerical data. So, it's a container for numbers.
Matrices are2d tensors; tensors are a generelization of matrices to an arbitrary number of dimensions.
(note that in the context of tensors, a dimension is often called an axis)



# Scalars (OD tensors)
A tensor that contains only one number is called a scalar(or scalar tensor, or 0-dimensional tensor, or 0D tensor). In Numpy
a float32 or float64 number is a scalar tensor (or scalar array). You can display the number of axes of a numpy tensor viaa
the ndim attribute; a scalar tensor has 0 axes (nim == 0).The number of axes of a tensor is also called its rank.

"""

x = np.array(12)

display(x)

display(x.ndim)

# Vectors (1d tensors)
# An array of numbers is called a vector, or 1d tensor. A 1d tensor is said to hace exactly one axis

xx= np.array([12, 3, 6, 14])

display(xx)

display(xx.ndim)

# This vector has five entries and so is called a 5-dimensional vector. Dont confuse a 5d vector with a 5d tesnor!
# A 5d vector has only one axis and has five dimensions along its axis,
# A 5d tensor has five axes (and may have any number of dimensions along each axis)
# Dimensionality can denote either the number of entries along a specific axis(as in case of 5d vector)
# or the umber of axes in a tensor (such as in a 5d tensor), 

# Matrices (2D tensors)

# An array of vectors is a matrix, or 2d tensor. A matrix has two axes (often referred to rows and colunms).
# you can visulaly interpert a matrix a as a rectangular grid of numbers.

x_ma = np.array([[5, 78, 2, 34, 0],
                [6, 79, 3, 35, 1],
                [7, 80, 4, 36, 2]])

display(x_ma)

display(x_ma.ndim)

# 3D tensors and higer dimensional tensors

# if you pack such matrices into a new array, you obtain a 3d tensor

xDDD = np.array([[[5, 78, 2, 34, 0],
                 [6, 79, 3, 35, 1],
                 [7, 80, 4, 36, 2]],
                [[5, 78, 2, 34, 0],
                 [6, 79, 3, 35, 1,
                 [7, 80, 4, 36, 2]],
                [[5, 78, 2, 34, 0],
                 [6, 79, 3, 35, 1],
                 [7, 80, 4, 36, 2]]]])

display(xDDD)

array(12)

0

array([12,  3,  6, 14])

1

array([[ 5, 78,  2, 34,  0],
       [ 6, 79,  3, 35,  1],
       [ 7, 80,  4, 36,  2]])

2

array([[list([5, 78, 2, 34, 0]), list([6, 79, 3, 35, 1]),
        list([7, 80, 4, 36, 2])],
       [list([5, 78, 2, 34, 0]),
        list([6, 79, 3, 35, 1, [7, 80, 4, 36, 2]]),
        list([[5, 78, 2, 34, 0], [6, 79, 3, 35, 1], [7, 80, 4, 36, 2]])]],
      dtype=object)